project:
  type: book
  output-dir: _book

lang: zh

book:
  title: "空间数据科学与 R 语言"
  subtitle: "探索和实践"
  output-file: "sdsr"
  author: "黄湘云"
  date: "2022-04-05"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  site-url: https://evalparse.github.io/sdsr/
  repo-url: https://github.com/evalparse/sdsr/
  repo-branch: main
  repo-actions: [edit, issue, source]
  search: true
  downloads: [pdf]

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
    code-tools: true
    crossref:
      chapters: true
      eq-prefix: ""
  pdf:
    documentclass: ctexbook
    classoption: [UTF8,twoside,openany,table]
    keep-tex: false
    lof: true
    lot: true
    toc: true
    toc-depth: 3
    geometry:
      - tmargin=2.5cm
      - bmargin=2.5cm
      - lmargin=3.0cm
      - rmargin=2.0cm
    highlight-style: github
    number-sections: true
    top-level-division: chapter
    colorlinks: true
    link-citations: true
    crossref:
      chapters: true
      eq-prefix: ""

editor: visual

